# @package _global_
env_type: halfcheetah
env_name: halfcheetah-bullet-medium-v0

algorithm: GAIL
training:
  batch_size: 1024
reinforcement:
  learning_rate: 0.00003
  ppo_epochs: 10
  entropy_loss_coeff: 0.01
imitation:
  epochs: 25
  learning_rate: 0.00003
  replay_size: 5
  r1_reg_coeff: 0.5
