# @package _global_
env_type: hopper
env_name: hopper-bullet-medium-v0

algorithm: GAIL
training:
  batch_size: 2048
reinforcement:
  learning_rate: 0.0003
  ppo_epochs: 10
  entropy_loss_coeff: 0.01
imitation:
  epochs: 5
  learning_rate: 0.0003
  replay_size: 3
  r1_reg_coeff: 1.0
