# @package _global_
env_type: walker2d
env_name: walker2d-bullet-medium-v0

algorithm: GAIL
training:
  batch_size: 1024
reinforcement:
  learning_rate: 0.0003
  ppo_epochs: 20
  entropy_loss_coeff: 0.0
imitation:
  epochs: 5
  learning_rate: 0.0003
  replay_size: 1
  r1_reg_coeff: 0.1
