# @package _global_
env_type: ant
env_name: ant-bullet-medium-v0

algorithm: RED
training:
  batch_size: 1024
reinforcement:
  learning_rate: 0.00003
  ppo_epochs: 10
  entropy_loss_coeff: 0.001
imitation:
  epochs: 15
  learning_rate: 0.00003
