# @package _global_
env_type: hopper
env_name: hopper-bullet-medium-v0

algorithm: RED
training:
  batch_size: 2048
reinforcement:
  learning_rate: 0.00003
  ppo_epochs: 10
  entropy_loss_coeff: 0.0
imitation:
  epochs: 25
  learning_rate: 0.0003
